In [1]:
import numpy as np

In [11]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
type(arr)

numpy.ndarray

In [4]:
np.__version__

'1.24.3'

In [5]:
arr = np.array((1, 2, 3, 4, 5))
arr

array([1, 2, 3, 4, 5])

In [6]:
arr = np.array({1, 2, 3, 4, 5})
arr

array({1, 2, 3, 4, 5}, dtype=object)

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr = np.array({"one":1, "two":2})
arr

array({'one': 1, 'two': 2}, dtype=object)

In [9]:
type(arr)

numpy.ndarray

In [14]:
# 0-D array
arr = np.array(46)
arr


array(46)

In [15]:
# ndim attribute used to find the dimension of the array
arr.ndim

0

In [16]:
# 1-D array
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [17]:
arr.ndim

1

In [18]:
# 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr.ndim

2

In [20]:
# 3-D array
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [21]:
arr.ndim

3

In [22]:
# we can using any dimensional array using ndmin attribute
# 5-D array
arr = np.array([1, 2, 3, 4], ndmin=5)
arr

array([[[[[1, 2, 3, 4]]]]])

In [23]:
arr.ndim

5

In [24]:
# 6-D array
arr = np.array([[[[[[4,5,6]]]]]],ndmin=6)
arr

array([[[[[[4, 5, 6]]]]]])

In [56]:
# accessing using index number
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[-1])
print(arr[-4])
print(arr[0:])
print(arr[:])
print(arr[1:])
print(arr[-4:])
print(arr[-4:-1])

1
4
1
[1 2 3 4]
[1 2 3 4]
[2 3 4]
[1 2 3 4]
[1 2 3]


In [60]:
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [61]:
print(arr[0])
print(arr[1])
print(arr[-1])
print(arr[-2])

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 6  7  8  9 10]
[1 2 3 4 5]


In [62]:
print(arr[:])
print(arr[0:1])
print(arr[-1:])
print(arr[-2:])
print(arr[-2:-1])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3 4 5]]
[[ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3 4 5]]


In [66]:
print(arr[0,4])
print(arr[0,0])
print(arr[1,4])
print(arr[-1,-3])
print(arr[-2,4])

5
1
10
8
5


In [68]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[0:, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [70]:
arr[0:1,0:]

array([[1, 2, 3, 4, 5]])

In [71]:
arr[0:,3]

array([4, 9])

In [72]:
# we know datatype all elements in array are same 
# to find datatype of elements in array , we can use "dtype" attribute
arr.dtype

dtype('int32')

In [73]:
arr = np.array(['apple', 'banana', 'cherry'])
arr.dtype

dtype('<U6')

In [98]:
# Creating array by explicitly giving datatype
# integer datatypes
# there are i,i1,i2,i3,i4
arr = np.array([1, 2, 3, -4], dtype='i')
print(arr)
arr.dtype

[ 1  2  3 -4]


dtype('int32')

In [100]:
# Unsigned integer datatypes
# there are u1,u2,u4,u8
arr = np.array([1, 2, 3, 4], dtype='u8')
print(arr)
arr.dtype

[1 2 3 4]


dtype('uint64')

In [116]:
# Floating-Point Data Types
# there are f,,f2,f4,f8,d,g
arr = np.array([1, 2, 3, 4], dtype='g')
print(arr)
arr.dtype

[1. 2. 3. 4.]


dtype('float64')

In [121]:
# Complex Data Types
# they are c8,c16
arr = np.array([1, 2, 3, 4], dtype='c8')
print(arr)
arr.dtype

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


dtype('complex64')

In [125]:
# Boolean Data Type
arr = np.array([1, 2, 3, 4], dtype='bool')
print(arr)
arr.dtype

[ True  True  True  True]


dtype('bool')

In [129]:
# String Data Types
# they are S,U
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
arr.dtype

[b'1' b'2' b'3' b'4']


dtype('S1')

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='O')
print(arr)