In [1]:
import numpy as np

In [2]:
# splitting using array_split()
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
newarr = np.array_split(arr,3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [4]:
newarr[0]

array([1, 2])

In [7]:
newarr = np.array_split(arr,6)
newarr

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]

In [8]:
newarr[2]

array([3])

In [9]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [16]:
newarr = np.array_split(arr,3,axis=0)
newarr

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [18]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [19]:
newarr = np.array_split(arr, 3)
newarr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]