In [2]:
import numpy as np

In [4]:
import numpy as np
arr = np.array([41, 42, 43, 44,45])
x = [True, False, True, False,True]
newarr = arr[x]
newarr

array([41, 43, 45])

In [5]:
arr = np.array([41,42,43,44])
filter_arr = []
for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
newarr = arr[filter_arr]
print(filter_arr)
newarr

[False, False, True, True]


array([43, 44])

In [6]:
arr = np.array([1,2,3,4,5,6,7])
filter_arr = []
for element in arr:
    if element%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
newarr = arr[filter_arr]
print(filter_arr)
newarr

[False, True, False, True, False, True, False]


array([2, 4, 6])

In [8]:
arr = np.array([41,42,43,44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
newarr

[False False  True  True]


array([43, 44])

In [9]:
arr = np.array([1,2,3,4,5,6,7])
filter_arr = arr%2 == 0
newarr = arr[filter_arr]
newarr

array([2, 4, 6])