In [1]:
import numpy as np

In [15]:
# concatenate()
# joining 1-D array
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2),axis=-0)
arr

array([1, 2, 3, 4, 5, 6])

In [30]:
# joining 2-D array
arr1=np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2),axis=0)
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [40]:
# stack function
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])
arr = np.stack((arr1,arr2,arr3),axis=1)
print(arr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [45]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
arr = np.stack((arr1,arr2),axis=2)
print(arr)

[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]


In [46]:
# hstack - to stack along row
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [47]:
# vstack- to stack along coloumn
arr1 =np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [48]:
# dstack - to stack along height
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
