In [2]:
import numpy as np

In [4]:
# copy
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
x = arr.copy()
x

array([1, 2, 3, 4, 5])

In [8]:
arr[0] = 100
print(arr)
print(x)

[100   2   3   4   5]
[200   2   3   4   5]


In [9]:
x[0] = 200
print(x)
print(arr)

[200   2   3   4   5]
[100   2   3   4   5]


In [10]:
# from the above we understand that ,changes made to the copied and original array not affeced by each other

In [11]:
# view
y = arr.view()
y

array([100,   2,   3,   4,   5])

In [12]:
arr[0] = 1000
print(arr)
print(y)

[1000    2    3    4    5]
[1000    2    3    4    5]


In [13]:
y[0] = 2000
print(y)
print(arr)

[2000    2    3    4    5]
[2000    2    3    4    5]


In [1]:
# from the above we understand that ,changes made to the viwed and original array are affeced by each other

In [3]:
arr = np.array([1,2,3,4,5])
x=arr.copy()
y= arr.view()

In [4]:
print(arr)
print(x)
print(y)

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [5]:
print(arr.base)
print(x.base)
print(y.base)

None
None
[1 2 3 4 5]


In [ ]:
# from above we understand that base attribute of original and copied array are None and viewd's array is its own