In [4]:
import numpy as np

In [2]:
# we know datatype all elements in array are same 
# to find datatype of elements in array , we can use "dtype" attribute
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr.dtype

dtype('int32')

In [3]:
arr = np.array(['apple', 'banana', 'cherry'])
arr.dtype

dtype('<U6')

In [4]:
# Creating array by explicitly giving datatype
# integer datatypes
# there are i,i1,i2,i3,i4
arr = np.array([1, 2, 3, -4], dtype='i')
print(arr)
arr.dtype

[ 1  2  3 -4]


dtype('int32')

In [5]:
# Unsigned integer datatypes
# there are u1,u2,u4,u8
arr = np.array([1, 2, 3, 4], dtype='u8')
print(arr)
arr.dtype

[1 2 3 4]


dtype('uint64')

In [6]:
# Floating-Point Data Types
# there are f,,f2,f4,f8,d,g
arr = np.array([1, 2, 3, 4], dtype='g')
print(arr)
arr.dtype

[1. 2. 3. 4.]


dtype('float64')

In [7]:
# Complex Data Types
# they are c8,c16
arr = np.array([1, 2, 3, 4], dtype='c8')
print(arr)
arr.dtype

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


dtype('complex64')

In [8]:
# Boolean Data Type
arr = np.array([1, 2, 3, 4], dtype='bool')
print(arr)
arr.dtype

[ True  True  True  True]


dtype('bool')

In [9]:
# String Data Types
# they are S,U
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
arr.dtype

[b'1' b'2' b'3' b'4']


dtype('S1')

In [11]:
# Object Data Type
arr = np.array([1, 2, 3, 4], dtype='O')
print(arr)
arr.dtype

[1 2 3 4]


dtype('O')

In [6]:
# DateTime Data Types
# they are M,m
arr = np.array([1, 2, 3, 4], dtype='m')
print(arr)
arr.dtype

[1 2 3 4]


dtype('<m8')

In [30]:
# we can change the datatype of an array to other using astype()
new_arr = arr.astype("i")
new_arr

array([1, 2, 3, 4], dtype=int32)

In [31]:
new_arr = arr.astype("bool")
new_arr

array([ True,  True,  True,  True])