In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6])
print(arr)
arr<3

[1 2 3 4 5 6]


array([ True,  True, False, False, False, False])

In [7]:
arr[arr<3]

array([1, 2])

In [8]:
arr*2

array([ 2,  4,  6,  8, 10, 12])

In [9]:
arr/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [10]:
arr%2

array([1, 0, 1, 0, 1, 0], dtype=int32)

In [11]:
# ones()
arr = np.ones((2,3,2),dtype='float')
arr

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [14]:
arr = np.ones((2,3),dtype='int')
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
# zeros()
arr = np.zeros((2,2,5),dtype='float')
arr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [17]:
arr = np.zeros((2,2),dtype='int')
arr

array([[0, 0],
       [0, 0]])

In [18]:
# broadcasting
arr = np.array([1,2,3,4,5,6])
print(arr)
arr[3:]=100
arr

[1 2 3 4 5 6]


array([  1,   2,   3, 100, 100, 100])

In [19]:
arr[:]=200
arr

array([200, 200, 200, 200, 200, 200])

In [20]:
#arange()
arr = np.arange(0,10,2,dtype='float')
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[0. 2. 4. 6. 8.]


In [21]:
#arange()
arr = np.arange(0,100,2,dtype='float')
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34.
 36. 38. 40. 42. 44. 46. 48. 50. 52. 54. 56. 58. 60. 62. 64. 66. 68. 70.
 72. 74. 76. 78. 80. 82. 84. 86. 88. 90. 92. 94. 96. 98.]
