In [1]:
import numpy as np

In [7]:
x = np.random.randint(100)
x

38

In [8]:
x = np.random.rand(2,2)
x

array([[0.81297431, 0.97187644],
       [0.04470496, 0.65455958]])

In [9]:
x = np.random.randint(10,20,size=(4,8))
x

array([[14, 11, 17, 10, 11, 15, 16, 10],
       [16, 16, 15, 11, 14, 17, 18, 10],
       [13, 17, 19, 17, 19, 19, 14, 17],
       [16, 12, 16, 11, 12, 19, 15, 18]])

In [10]:
x = np.random.randint(100,size=(2,2,2))
x


array([[[ 7, 34],
        [43, 56]],

       [[53, 19],
        [98, 69]]])

In [11]:
x = np.random.rand(2)
x

array([0.63629796, 0.0658498 ])

In [15]:
x = np.random.choice([1,45,6,7,90])
x

45

In [16]:
x = np.random.choice([1,4,5,8,9],size=(5,1,6))
x

array([[[9, 4, 9, 1, 1, 8]],

       [[4, 4, 4, 1, 8, 9]],

       [[9, 4, 8, 1, 9, 1]],

       [[8, 4, 5, 5, 8, 1]],

       [[1, 1, 9, 1, 8, 9]]])

In [18]:
x = np.random.choice([1,4,5,8,9],size=(5,5))
x

array([[4, 1, 5, 8, 1],
       [9, 4, 9, 1, 1],
       [5, 4, 4, 8, 4],
       [4, 4, 5, 1, 4],
       [4, 1, 9, 9, 1]])

In [19]:
x = np.random.choice([1,4,5,8,9],size=(2,2,2))
x

array([[[4, 8],
        [8, 4]],

       [[4, 4],
        [1, 9]]])

In [24]:
x = np.random.random(8)
x

array([0.87067753, 0.77969004, 0.91883367, 0.65362406, 0.41570392,
       0.74713746, 0.59157648, 0.18501546])

In [26]:
x = np.random.rand(2,2,4)
x

array([[[0.30228243, 0.50511695, 0.11052444, 0.45817551],
        [0.14231957, 0.71837102, 0.93021094, 0.00917231]],

       [[0.4254415 , 0.90039214, 0.21470234, 0.74731485],
        [0.6677818 , 0.76357731, 0.13865151, 0.60650553]]])

In [33]:
arr = [1,2,8,9,0,5,7]
x = np.random.shuffle(arr)
arr

[7, 0, 9, 2, 5, 8, 1]

In [35]:
x = np.random.permutation([1,2,5,6,9,0])
x

array([9, 1, 5, 6, 2, 0])

In [38]:
x = np.random.sample(10)
x

array([0.88905376, 0.52207406, 0.13701721, 0.8501269 , 0.15462381,
       0.06778197, 0.19231217, 0.12181213, 0.93278369, 0.50023698])