In [1]:
import numpy as np

In [8]:
# shape 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.ndim)
arr.shape

[[1 2 3 4]
 [5 6 7 8]]
2


(2, 4)

In [9]:
arr = np.array([1, 2, 3, 4])
print(arr.ndim)
print(arr.shape)

1
(4,)


In [10]:
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [14]:
# maximum range of dimensions are 32
arr = np.array([1,2,3,4],ndmin=32)
arr

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2,
                                      3, 4]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [15]:
arr.shape

(1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 4)

In [25]:
# reshape from 1D-2D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)
print('--------------')
newarr = arr.reshape(3,4)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
new = arr.reshape(12,1)
print(new)
new = arr.reshape(1,12)
print(new)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [28]:
# reshape 1D in to 3D 
new = arr.reshape(2,2,3)
print(new)
print('-----------')
print(new.base)
print('-----------')
new = arr.reshape(3,2,2)
print(new)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
-----------
[ 1  2  3  4  5  6  7  8  9 10 11 12]
-----------
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [29]:
# reshape
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.ndim)
new = arr.reshape(-1)
print(new)
print(new.ndim)

[[1 2 3]
 [4 5 6]]
2
[1 2 3 4 5 6]
1


In [30]:
# reshape method is used to change the any dimensional array in to 1D

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]],ndmin=32)
print(arr)
arr.reshape(-1)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3]
                               [4 5 6]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


array([1, 2, 3, 4, 5, 6])

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)
print(arr.shape)
print('---------------')
print(arr.reshape(4,2))
arr.reshape(4,2).base

[1 2 3 4 5 6 7 8]
(8,)
---------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


array([1, 2, 3, 4, 5, 6, 7, 8])