In [1]:
import numpy as np

In [2]:
# numpy searching
arr = np.array([1,2,3,4,5,4,4,])
arr

array([1, 2, 3, 4, 5, 4, 4])

In [3]:
x = np.where(arr==4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [4]:
arr = np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
x = np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [6]:
x = np.where(arr%2==1)
x

(array([0, 2, 4, 6], dtype=int64),)

In [7]:
x = np.where(arr==7)
x

(array([6], dtype=int64),)

In [11]:
# searchsorted from left
arr = np.array([6,7,8,9])
x= np.searchsorted(arr,7,side="left")
x

1

In [13]:
x= np.searchsorted(arr,7)
x

1

In [14]:
x= np.searchsorted(arr,7,side="right")
x

2

In [15]:
arr = np.array([3,2,0,1])
arr

array([3, 2, 0, 1])

In [17]:
# sort
sorted_re = np.sort(arr)
sorted_re

array([0, 1, 2, 3])

In [18]:
arr = np.array(['banana','cherry','apppe'])
np.sort(arr)

array(['apppe', 'banana', 'cherry'], dtype='<U6')

In [19]:
arr = np.array([True,False,True])
arr

array([ True, False,  True])

In [20]:
np.sort(arr)

array([False,  True,  True])

In [8]:
arr = np.array([[3,2,4],[5,0,1]])
np.sort(arr)

array([[2, 3, 4],
       [0, 1, 5]])